--local lsp = require("lsp-zero")
--
--lsp.preset("recommended")
--
--lsp.ensure_installed({
--  "clangd",
--})
--
--lsp.nvim_workspace()
--
--local cmp = require('cmp')
--
--lsp.setup_nvim_cmp({
--    mapping = {
--        ['<CR>'] = vim.NIL
--    },
--    completion = {
--        autocomplete = false
--    }
--})
--
--lsp.set_preferences({
--    suggest_lsp_servers = false,
--    sign_icons = {
--        error = 'E',
--        warn = 'W',
--        hint = 'H',
--        info = 'I'
--    },
--})
--
--lsp.on_attach(function(client, bufnr)
--  local opts = {buffer = bufnr, remap = true}
--
--  vim.keymap.set("n", "gd", function() vim.lsp.buf.definition() end, opts)
--  vim.keymap.set("n", "K", function() vim.lsp.buf.hover() end, opts)
--  vim.keymap.set("n", "<leader>vrr", function() vim.lsp.buf.references() end, opts)
--  vrm.keymap.set("n", "<leader>vrn", function() vim.lsp.buf.rename() end, opts)
--end)
--
--lsp.setup()
--
--vim.diagnostic.config({
--    virtual_text = false,
--    signs = false,
--    underline = false,
--})
----
